/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.mpgc.rpg130730;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testTest() {
        assertTrue(true);
    }
}
